### PR TITLE
NavigationStackCompat name changed to support Xcode 14

### PR DESCRIPTION
**Pull request by Sadmansamee**

### CODE REVIEW

**Comment by Sadmansamee** [comment]
#75 #72

**Comment by matteopuc** [comment]
Hi @Sadmansamee thank you so much for your help. Correct me if I'm wrong: you changed `NavigationStack` to `NavigationStackCompat` and `NavigationStackView` to `NavigationStackCompat`. Let's use two different names for the two different entities. It's ok to rename `NavigationStack` to `NavigationStackCompat` (this is mandatory since Apple has created it's own `NavigationStack`) but maybe we can leave `NavigationStackView` as it is. Or maybe we can change it to `NavigationStackViewCompat`. Thanks!

**Comment by Sadmansamee** [comment]
It was definitely a type, I'll make changes

**Comment by Sadmansamee** [comment]
@matteopuc I have made changes

**Comment by Sadmansamee** [comment]
@matteopuc could have a look into this?

**Comment by matteopuc** [comment]
Thanks for your help!

**Comment by domfz** [comment]
The readme for this change wasn't updated.

**Pull request merged**
